### ISSUE TITLE
[REQUEST] Custom shortcuts

### ISSUE THREAD

**Issue by JPenuchot** [loggerhead/Layout#7]
CTRL + W is the default shortcut to close a tab on AZERTY keyboards, I really love this plugin but sadly it's quite a pain on French keyboards

**Comment by loggerhead** [comment]
Of course you can custom shortcuts, just check https://github.com/loggerhead/Layout/blob/master/Default.sublime-keymap 😄

**Comment by JPenuchot** [comment]
My bad !
