### ISSUE TITLE
alt+L replaces @ sign on macOS

### ISSUE THREAD

**Issue by ccarstens** [loggerhead/Layout#8]
Hey,

thank you loggerhead for making Layout, I love it and this is one of the packages that should be part of sublime instead of their default layout handling.

When Installing Layout on a mac the "increase pane width to the right" shortcut "alt+l" replaces the @ sign on the mac. I solved it by giving it an arbitrary key binding.

Is there also a way of defining a User.sublime-keymap for Layout?

Thank you,
kind regards,
ccarstens

**Comment by loggerhead** [comment]
Yes, just edit `User/Default.sublime-keymap`, custom any commands you want (refer https://raw.githubusercontent.com/loggerhead/Layout/master/Default.sublime-keymap).
